title: "[Esame 0 Mese 0000] Esercizio 0"
labels: ["da risolvere"]
body: 
- type: dropdown
  id: category
  attributes:
    label: Che tipo di esercizio è?
    options:
      - algebra relazionale
      - teoria relazionale
      - organizzazione fisica
      - altro
  validations:
    required: true
- type: markdown
  attributes:
    value: "## Scrivi il testo dell'esercizio o posta uno screenshot!"
- type: textarea
  id: esercizio
  attributes:
    label: Testo dell'esercizio
    description: "Scrivi il testo dell'esercizio o posta uno screenshot!"
    placeholder: "Esercizio..."
    render: bash
  validations:
    required: true
